"""Added company name to user

Revision ID: 42312030c979
Revises: e56324d0d2b2
Create Date: 2026-07-02 14:52:19.857098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42312030c979'
down_revision = 'e56324d0d2b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('company_name')

    # ### end Alembic commands ###
